name: DropClear
main: com.miraclem4n.dropclear.DropClear
version: ${m.version}-${build.number}-${p.version}
author: MiracleM4n
description: Provides Clearing drops/mobs in a radius.
commands:
    dropclear:
        description: Destroy all nearby drops/mobs.
        usage: |
            /<command> [radius]
            Example: /<command> - See this info.
            Example: /<command> drop 30 - Clear drops in a radius of 30.
            Example: /<command> mob 10 - Clear mobs in a radius of 10.
        aliases: [dc, dclear]